apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"    # sau namespace, truoc workloads
data:
  API_URL: "http://api:8080"
